// #[cfg(test)]
pub mod test_salvo {

    use salvo::prelude::*;

    #[fn_handler]
    async fn hello_world() -> &'static str {
        "hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hhello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework 
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hhello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework 
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hhello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework 
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hhello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework 
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hhello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework 
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hhello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework 
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hhello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework 
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hhello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework 
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hhello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework 
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hhello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework 
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework
hello world this is from salvo web framework hello world this is from salvo web framework hello world this is from salvo web framework

"
    }

    // #[tokio::test]
    async fn test_hello() {
        let router = Router::new().path("/hello").get(hello_world);
        Server::new(router).bind(([0, 0, 0, 0], 7878)).await;
    }
}
